export const auditFields = {
  createdAt: new Date(),
  updatedAt: new Date(),
  deletedAt: null,
};

export const TEST_USER_A_ID = 'TEST_USER_A_ID';

export const TEST_USER_B_ID = 'TEST_USER_B_ID';

export const PROJECT_ID = 'TEST_PROJECT_ID';

export const PROJECT_ORGANIZATION_A_ID = 'TEST_PROJECT_ORGANIZATION_A_ID';

export const PROJECT_ORGANIZATION_B_ID = 'TEST_PROJECT_ORGANIZATION_B_ID';

export const ORGANIZATION_A_USER_A_ID = 'ORGANIZATION_A_USER_A_ID';

export const ORGANIZATION_A_USER_B_ID = 'ORGANIZATION_A_USER_B_ID';

export const PROJECT_ROLE_ADMIN_ID = 'ROLE_ADMIN_ID';

export const PROJECT_ROLE_USER_ID = 'ROLE_USER_ID';

export const KEY_MANAGEMENT_A_ID = 'KEY_MANAGEMENT_A_ID';

export const KEY_MANAGEMENT_B_ID = 'KEY_MANAGEMENT_B_ID';

export const ORGANIZATION_KEY_MANAGEMENT_A_ID =
  'ORGANIZATION_KEY_MANAGEMENT_A_ID';

export const ORGANIZATION_KEY_MANAGEMENT_B_ID =
  'ORGANIZATION_KEY_MANAGEMENT_B_ID';
